# Generated by Django 4.2.1 on 2023-06-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
    ]
