# Generated by Django 4.2.1 on 2023-06-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='question',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tags_text',
            field=models.CharField(default='test_tag', max_length=200),
        ),
    ]
