# Generated by Django 4.2.1 on 2023-06-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_tags_question_alter_tags_tags_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
